name: Deploy to Banjo Web Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via SFTP
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: banjo.rit.edu
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: "www"
          remoteDir: "/home/${{ secrets.USERNAME }}/www"
